.weak
      rlGetSelectedUnitFatherID       :?= address($84A43D)
      rlSetSelectedUnitTalkTarget       :?= address($849EF7)
      rlCreateProcHaltEvent             :?= address($829478)
      rlLoadWorldMapPortraitIntoSlot     :?= address($8682BC)
      rlASMCGiveToSupplyMenuIfInventoryFull            :?= address($8B8345)
      rlGetSelectedUnitDeploymentOffset :?= address($84966B)
      rlDeployedUnitUnsetHiddenIfAlive     :?= address($84CB83)
      rlClearBattleData     :?= address($84DE18)
      rlGetUnitRAMDataPointerByID     :?= address($8484B4)
      rlASMCLoadActiveUnitCoordinatesInEventUnitSlot1     :?= address($91b08e)
      rlASMCShowItemPopUpBox                  :?= address($81B223)
        rlASMCGiveToSupplyMenuIfInventoryFull   :?= address($81B259)
        rlASMCGiveJuliaLightIfNoWeapon          :?= address($86C6A2)
        rlASMCStatUpDisplay                     :?= address($91BD94)
      rlGetItemIDByInventorySlot     :?= address($84F38B)
      rlASMCRefreshAllUnits     :?= address($B298FF)
      rlBuildRAMStructHeader     :?= address($82E41B)
      rlAppendNewStructEntry     :?= address($82E465)
      rlFindGenerationIDInFactionSlotData     :?= address($84BF67)
      rlGetSelectedUnitStates     :?= address($8495E5)
      rlDeployedUnitSetHidden     :?= address($84CBBC)
      rlEventEngineCreateProc     :?= address($91A455)
      rlGetSelectedUnitLevel     :?= address($849E23)
      rlGetSelectedUnitFirstInventoryItem     :?= address($84F2EB)
    .endweak