
    structGen2LoveMLMEntry .struct SeliphSeliph, SeliphShannan, SeliphDalvin, SeliphAsaello, SeliphLeif, SeliphIuchar, SeliphCharlot, SeliphHawk, SeliphTristan, SeliphAdultFinn, SeliphDeimne, SeliphHannibal, SeliphAres, SeliphAmid, SeliphOifey, SeliphIucharba, SeliphScathach, SeliphFebail, SeliphCoirpre, SeliphCed, SeliphDiarmuid, SeliphLester, SeliphArthur, ShannanShannan, ShannanDalvin, ShannanAsaello, ShannanLeif, ShannanIuchar, ShannanCharlot, ShannanHawk, ShannanTristan, ShannanAdultFinn, ShannanDeimne, ShannanHannibal, ShannanAres, ShannanAmid, ShannanOifey, ShannanIucharba, ShannanScathach, ShannanFebail, ShannanCoirpre, ShannanCed, ShannanDiarmuid, ShannanLester, ShannanArthur, DalvinDalvin, DalvinAsaello, DalvinLeif, DalvinIuchar, DalvinCharlot, DalvinHawk, DalvinTristan, DalvinAdultFinn, DalvinDeimne, DalvinHannibal, DalvinAres, DalvinAmid, DalvinOifey, DalvinIucharba, DalvinScathach, DalvinFebail, DalvinCoirpre, DalvinCed, DalvinDiarmuid, DalvinLester, DalvinArthur, AsaelloAsaello, AsaelloLeif, AsaelloIuchar, AsaelloCharlot, AsaelloHawk, AsaelloTristan, AsaelloAdultFinn, AsaelloDeimne, AsaelloHannibal, AsaelloAres, AsaelloAmid, AsaelloOifey, AsaelloIucharba, AsaelloScathach, AsaelloFebail, AsaelloCoirpre, AsaelloCed, AsaelloDiarmuid, AsaelloLester, AsaelloArthur, LeifLeif, LeifIuchar, LeifCharlot, LeifHawk, LeifTristan, LeifAdultFinn, LeifDeimne, LeifHannibal, LeifAres, LeifAmid, LeifOifey, LeifIucharba, LeifScathach, LeifFebail, LeifCoirpre, LeifCed, LeifDiarmuid, LeifLester, LeifArthur,IucharIuchar, IucharCharlot, IucharHawk, IucharTristan, IucharAdultFinn,  IucharDeimne, IucharHannibal, IucharAres,  IucharAmid,  IucharOifey, IucharIucharba, IucharScathach, IucharFebail, IucharCoirpre, IucharCed, IucharDiarmuid, IucharLester, IucharArthur, CharlotCharlot, CharlotHawk, CharlotTristan, CharlotAdultFinn, CharlotDeimne, CharlotHannibal, CharlotAres, CharlotAmid, CharlotOifey, CharlotIucharba, CharlotScathach, CharlotFebail, CharlotCoirpre, CharlotCed, CharlotDiarmuid, CharlotLester, CharlotArthur, HawkHawk, HawkTristan, HawkAdultFinn, HawkDeimne, HawkHannibal, HawkAres, HawkAmid, HawkOifey, HawkIucharba, HawkScathach, HawkFebail, HawkCoirpre, HawkCed, HawkDiarmuid, HawkLester, HawkArthur, TristanTristan, TristanAdultFinn, TristanDeimne, TristanHannibal, TristanAres, TristanAmid, TristanOifey, TristanIucharba, TristanScathach, TristanFebail, TristanCoirpre, TristanCed, TristanDiarmuid, TristanLester, TristanArthur, AdultFinnAdultFinn, AdultFinnDeimne, AdultFinnHannibal, AdultFinnAres, AdultFinnAmid, AdultFinnOifey, AdultFinnIucharba, AdultFinnScathach, AdultFinnFebail, AdultFinnCoirpre, AdultFinnCed, AdultFinnDiarmuid, AdultFinnLester, AdultFinnArthur, DeimneDeimne, DeimneHannibal, DeimneAres, DeimneAmid, DeimneOifey, DeimneIucharba, DeimneScathach, DeimneFebail, DeimneCoirpre, DeimneCed, DeimneDiarmuid, DeimneLester, DeimneArthur, HannibalHannibal, HannibalAres, HannibalAmid, HannibalOifey, HannibalIucharba, HannibalScathach, HannibalFebail, HannibalCoirpre, HannibalCed, HannibalDiarmuid, HannibalLester, HannibalArthur, AresAres, AresAmid, AresOifey, AresIucharba, AresScathach, AresFebail, AresCoirpre, AresCed, AresDiarmuid, AresLester, AresArthur, AmidAmid, AmidOifey, AmidIucharba, AmidScathach, AmidFebail, AmidCoirpre, AmidCed, AmidDiarmuid, AmidLester, AmidArthur, OifeyOifey, OifeyIucharba, OifeyScathach, OifeyFebail, OifeyCoirpre, OifeyCed, OifeyDiarmuid, OifeyLester, OifeyArthur, IucharbaIucharba, IucharbaScathach, IucharbaFebail, IucharbaCoirpre, IucharbaCed, IucharbaDiarmuid, IucharbaLester, IucharbaArthur, ScathachScathach, ScathachFebail, ScathachCoirpre, ScathachCed, ScathachDiarmuid, ScathachLester, ScathachArthur, FebailFebail, FebailCoirpre, FebailCed, FebailDiarmuid, FebailLester, FebailArthur, CoirpreCoirpre, CoirpreCed, CoirpreDiarmuid, CoirpreLester, CoirpreArthur, CedCed, CedDiarmuid, CedLester, CedArthur, DiarmuidDiarmuid, DiarmuidLester, DiarmuidArthur, LesterLester, LesterArthur, ArthurArthur
.char \SeliphSeliph
.char \SeliphShannan
.char \SeliphDalvin
.char \SeliphAsaello
.char \SeliphLeif
.char \SeliphIuchar
.char \SeliphCharlot
.char \SeliphHawk
.char \SeliphTristan
.char \SeliphAdultFinn
.char \SeliphDeimne
.char \SeliphHannibal
.char \SeliphAres
.char \SeliphAmid
.char \SeliphOifey
.char \SeliphIucharba
.char \SeliphScathach
.char \SeliphFebail
.char \SeliphCoirpre
.char \SeliphCed
.char \SeliphDiarmuid
.char \SeliphLester
.char \SeliphArthur
.char \ShannanShannan
.char \ShannanDalvin
.char \ShannanAsaello
.char \ShannanLeif
.char \ShannanIuchar
.char \ShannanCharlot
.char \ShannanHawk
.char \ShannanTristan
.char \ShannanAdultFinn
.char \ShannanDeimne
.char \ShannanHannibal
.char \ShannanAres
.char \ShannanAmid
.char \ShannanOifey
.char \ShannanIucharba
.char \ShannanScathach
.char \ShannanFebail
.char \ShannanCoirpre
.char \ShannanCed
.char \ShannanDiarmuid
.char \ShannanLester
.char \ShannanArthur
.char \DalvinDalvin
.char \DalvinAsaello
.char \DalvinLeif
.char \DalvinIuchar
.char \DalvinCharlot
.char \DalvinHawk
.char \DalvinTristan
.char \DalvinAdultFinn
.char \DalvinDeimne
.char \DalvinHannibal
.char \DalvinAres
.char \DalvinAmid
.char \DalvinOifey
.char \DalvinIucharba
.char \DalvinScathach
.char \DalvinFebail
.char \DalvinCoirpre
.char \DalvinCed
.char \DalvinDiarmuid
.char \DalvinLester
.char \DalvinArthur
.char \AsaelloAsaello
.char \AsaelloLeif
.char \AsaelloIuchar
.char \AsaelloCharlot
.char \AsaelloHawk
.char \AsaelloTristan
.char \AsaelloAdultFinn
.char \AsaelloDeimne
.char \AsaelloHannibal
.char \AsaelloAres
.char \AsaelloAmid
.char \AsaelloOifey
.char \AsaelloIucharba
.char \AsaelloScathach
.char \AsaelloFebail
.char \AsaelloCoirpre
.char \AsaelloCed
.char \AsaelloDiarmuid
.char \AsaelloLester
.char \AsaelloArthur
.char \LeifLeif
.char \LeifIuchar
.char \LeifCharlot
.char \LeifHawk
.char \LeifTristan
.char \LeifAdultFinn
.char \LeifDeimne
.char \LeifHannibal
.char \LeifAres
.char \LeifAmid
.char \LeifOifey
.char \LeifIucharba
.char \LeifScathach
.char \LeifFebail
.char \LeifCoirpre
.char \LeifCed
.char \LeifDiarmuid
.char \LeifLester
.char \LeifArthur
.char \IucharIuchar
.char \IucharCharlot
.char \IucharHawk
.char \IucharTristan
.char \IucharAdultFinn
.char \IucharDeimne
.char \IucharHannibal
.char \IucharAres
.char \IucharAmid
.char \IucharOifey
.char \IucharIucharba
.char \IucharScathach
.char \IucharFebail
.char \IucharCoirpre
.char \IucharCed
.char \IucharDiarmuid
.char \IucharLester
.char \IucharArthur
.char \CharlotCharlot
.char \CharlotHawk
.char \CharlotTristan
.char \CharlotAdultFinn
.char \CharlotDeimne
.char \CharlotHannibal
.char \CharlotAres
.char \CharlotAmid
.char \CharlotOifey
.char \CharlotIucharba
.char \CharlotScathach
.char \CharlotFebail
.char \CharlotCoirpre
.char \CharlotCed
.char \CharlotDiarmuid
.char \CharlotLester
.char \CharlotArthur
.char \HawkHawk
.char \HawkTristan
.char \HawkAdultFinn
.char \HawkDeimne
.char \HawkHannibal
.char \HawkAres
.char \HawkAmid
.char \HawkOifey
.char \HawkIucharba
.char \HawkScathach
.char \HawkFebail
.char \HawkCoirpre
.char \HawkCed
.char \HawkDiarmuid
.char \HawkLester
.char \HawkArthur
.char \TristanTristan
.char \TristanAdultFinn
.char \TristanDeimne
.char \TristanHannibal
.char \TristanAres
.char \TristanAmid
.char \TristanOifey
.char \TristanIucharba
.char \TristanScathach
.char \TristanFebail
.char \TristanCoirpre
.char \TristanCed
.char \TristanDiarmuid
.char \TristanLester
.char \TristanArthur
.char \AdultFinnAdultFinn
.char \AdultFinnDeimne
.char \AdultFinnHannibal
.char \AdultFinnAres
.char \AdultFinnAmid
.char \AdultFinnOifey
.char \AdultFinnIucharba
.char \AdultFinnScathach
.char \AdultFinnFebail
.char \AdultFinnCoirpre
.char \AdultFinnCed
.char \AdultFinnDiarmuid
.char \AdultFinnLester
.char \AdultFinnArthur
.char \DeimneDeimne
.char \DeimneHannibal
.char \DeimneAres
.char \DeimneAmid
.char \DeimneOifey
.char \DeimneIucharba
.char \DeimneScathach
.char \DeimneFebail
.char \DeimneCoirpre
.char \DeimneCed
.char \DeimneDiarmuid
.char \DeimneLester
.char \DeimneArthur
.char \HannibalHannibal
.char \HannibalAres
.char \HannibalAmid
.char \HannibalOifey
.char \HannibalIucharba
.char \HannibalScathach
.char \HannibalFebail
.char \HannibalCoirpre
.char \HannibalCed
.char \HannibalDiarmuid
.char \HannibalLester
.char \HannibalArthur
.char \AresAres
.char \AresAmid
.char \AresOifey
.char \AresIucharba
.char \AresScathach
.char \AresFebail
.char \AresCoirpre
.char \AresCed
.char \AresDiarmuid
.char \AresLester
.char \AresArthur
.char \AmidAmid
.char \AmidOifey
.char \AmidIucharba
.char \AmidScathach
.char \AmidFebail
.char \AmidCoirpre
.char \AmidCed
.char \AmidDiarmuid
.char \AmidLester
.char \AmidArthur
.char \OifeyOifey
.char \OifeyIucharba
.char \OifeyScathach
.char \OifeyFebail
.char \OifeyCoirpre
.char \OifeyCed
.char \OifeyDiarmuid
.char \OifeyLester
.char \OifeyArthur
.char \IucharbaIucharba
.char \IucharbaScathach
.char \IucharbaFebail
.char \IucharbaCoirpre
.char \IucharbaCed
.char \IucharbaDiarmuid
.char \IucharbaLester
.char \IucharbaArthur
.char \ScathachScathach
.char \ScathachFebail
.char \ScathachCoirpre
.char \ScathachCed
.char \ScathachDiarmuid
.char \ScathachLester
.char \ScathachArthur
.char \FebailFebail
.char \FebailCoirpre
.char \FebailCed
.char \FebailDiarmuid
.char \FebailLester
.char \FebailArthur
.char \CoirpreCoirpre
.char \CoirpreCed
.char \CoirpreDiarmuid
.char \CoirpreLester
.char \CoirpreArthur
.char \CedCed
.char \CedDiarmuid
.char \CedLester
.char \CedArthur
.char \DiarmuidDiarmuid
.char \DiarmuidLester
.char \DiarmuidArthur
.char \LesterLester
.char \LesterArthur
.char \ArthurArthur
    .endstruct

structGen2LoveWLWEntry .struct DaisyDaisy, DaisyCreidne, DaisyMuirne, DaisyJulia, DaisyAltena, DaisyHermina, DaisyLinda, DaisyLaylea, DaisyJeanne, DaisyPatty, DaisyLarcei, DaisyLana, DaisyFee, DaisyTine, DaisyLene, DaisyNanna, CreidneCreidne, CreidneMuirne, CreidneJulia, CreidneAltena, CreidneHermina, CreidneLinda, CreidneLaylea, CreidneJeanne, CreidnePatty, CreidneLarcei, CreidneLana, CreidneFee, CreidneTine, CreidneLene, CreidneNanna, MuirneMuirne, MuirneJulia, MuirneAltena, MuirneHermina, MuirneLinda, MuirneLaylea, MuirneJeanne, MuirnePatty, MuirneLarcei, MuirneLana, MuirneFee, MuirneTine, MuirneLene, MuirneNanna, JuliaJulia, JuliaAltena, JuliaHermina, JuliaLinda, JuliaLaylea, JuliaJeanne, JuliaPatty, JuliaLarcei, JuliaLana, JuliaFee, JuliaTine, JuliaLene, JuliaNanna, AltenaAltena, AltenaHermina, AltenaLinda, AltenaLaylea, AltenaJeanne, AltenaPatty, AltenaLarcei, AltenaLana, AltenaFee, AltenaTine, AltenaLene, AltenaNanna, HerminaHermina, HerminaLinda, HerminaLaylea, HerminaJeanne, HerminaPatty, HerminaLarcei, HerminaLana, HerminaFee, HerminaTine, HerminaLene, HerminaNanna, LindaLinda, LindaLaylea, LindaJeanne, LindaPatty, LindaLarcei, LindaLana, LindaFee, LindaTine, LindaLene, LindaNanna, LayleaLaylea, LayleaJeanne, LayleaPatty, LayleaLarcei, LayleaLana, LayleaFee, LayleaTine, LayleaLene, LayleaNanna, JeanneJeanne, JeannePatty, JeanneLarcei, JeanneLana, JeanneFee, JeanneTine, JeanneLene, JeanneNanna, PattyPatty, PattyLarcei, PattyLana, PattyFee, PattyTine, PattyLene, PattyNanna, LarceiLarcei, LarceiLana, LarceiFee, LarceiTine, LarceiLene, LarceiNanna, LanaLana, LanaFee, LanaTine, LanaLene, LanaNanna, FeeFee, FeeTine, FeeLene, FeeNanna, TineTine, TineLene, TineNanna, LeneLene, LeneNanna, NannaNanna
.char \DaisyDaisy
.char \DaisyCreidne
.char \DaisyMuirne
.char \DaisyJulia
.char \DaisyAltena
.char \DaisyHermina
.char \DaisyLinda
.char \DaisyLaylea
.char \DaisyJeanne
.char \DaisyPatty
.char \DaisyLarcei
.char \DaisyLana
.char \DaisyFee
.char \DaisyTine
.char \DaisyLene
.char \DaisyNanna
.char \CreidneCreidne
.char \CreidneMuirne
.char \CreidneJulia
.char \CreidneAltena
.char \CreidneHermina
.char \CreidneLinda
.char \CreidneLaylea
.char \CreidneJeanne
.char \CreidnePatty
.char \CreidneLarcei
.char \CreidneLana
.char \CreidneFee
.char \CreidneTine
.char \CreidneLene
.char \CreidneNanna
.char \MuirneMuirne
.char \MuirneJulia
.char \MuirneAltena
.char \MuirneHermina
.char \MuirneLinda
.char \MuirneLaylea
.char \MuirneJeanne
.char \MuirnePatty
.char \MuirneLarcei
.char \MuirneLana
.char \MuirneFee
.char \MuirneTine
.char \MuirneLene
.char \MuirneNanna
.char \JuliaJulia
.char \JuliaAltena
.char \JuliaHermina
.char \JuliaLinda
.char \JuliaLaylea
.char \JuliaJeanne
.char \JuliaPatty
.char \JuliaLarcei
.char \JuliaLana
.char \JuliaFee
.char \JuliaTine
.char \JuliaLene
.char \JuliaNanna
.char \AltenaAltena
.char \AltenaHermina
.char \AltenaLinda
.char \AltenaLaylea
.char \AltenaJeanne
.char \AltenaPatty
.char \AltenaLarcei
.char \AltenaLana
.char \AltenaFee
.char \AltenaTine
.char \AltenaLene
.char \AltenaNanna
.char \HerminaHermina
.char \HerminaLinda
.char \HerminaLaylea
.char \HerminaJeanne
.char \HerminaPatty
.char \HerminaLarcei
.char \HerminaLana
.char \HerminaFee
.char \HerminaTine
.char \HerminaLene
.char \HerminaNanna
.char \LindaLinda
.char \LindaLaylea
.char \LindaJeanne
.char \LindaPatty
.char \LindaLarcei
.char \LindaLana
.char \LindaFee
.char \LindaTine
.char \LindaLene
.char \LindaNanna
.char \LayleaLaylea
.char \LayleaJeanne
.char \LayleaPatty
.char \LayleaLarcei
.char \LayleaLana
.char \LayleaFee
.char \LayleaTine
.char \LayleaLene
.char \LayleaNanna
.char \JeanneJeanne
.char \JeannePatty
.char \JeanneLarcei
.char \JeanneLana
.char \JeanneFee
.char \JeanneTine
.char \JeanneLene
.char \JeanneNanna
.char \PattyPatty
.char \PattyLarcei
.char \PattyLana
.char \PattyFee
.char \PattyTine
.char \PattyLene
.char \PattyNanna
.char \LarceiLarcei
.char \LarceiLana
.char \LarceiFee
.char \LarceiTine
.char \LarceiLene
.char \LarceiNanna
.char \LanaLana
.char \LanaFee
.char \LanaTine
.char \LanaLene
.char \LanaNanna
.char \FeeFee
.char \FeeTine
.char \FeeLene
.char \FeeNanna
.char \TineTine
.char \TineLene
.char \TineNanna
.char \LeneLene
.char \LeneNanna
.char \NannaNanna
.endstruct

structGen1LoveMLMEntry .struct SigurdSigurd, SigurdNaoise, SigurdAlec, SigurdArden, SigurdFinn, SigurdQuan, SigurdMidir, SigurdLewyn, SigurdChulainn, SigurdAzelle, SigurdJamke, SigurdClaud, SigurdBeowolf, SigurdLex, SigurdDew, NaoiseNaoise, NaoiseAlec, NaoiseArden, NaoiseFinn, NaoiseQuan, NaoiseMidir, NaoiseLewyn, NaoiseChulainn, NaoiseAzelle, NaoiseJamke, NaoiseClaud, NaoiseBeowolf, NaoiseLex, NaoiseDew, AlecAlec, AlecArden, AlecFinn, AlecQuan, AlecMidir, AlecLewyn, AlecChulainn, AlecAzelle, AlecJamke, AlecClaud, AlecBeowolf, AlecLex, AlecDew, ArdenArden, ArdenFinn, ArdenQuan, ArdenMidir, ArdenLewyn, ArdenChulainn, ArdenAzelle, ArdenJamke, ArdenClaud, ArdenBeowolf, ArdenLex, ArdenDew, FinnFinn, FinnQuan, FinnMidir, FinnLewyn, FinnChulainn, FinnAzelle, FinnJamke, FinnClaud, FinnBeowolf, FinnLex, FinnDew, QuanQuan, QuanMidir, QuanLewyn, QuanChulainn, QuanAzelle, QuanJamke, QuanClaud, QuanBeowolf, QuanLex, QuanDew, MidirMidir, MidirLewyn, MidirChulainn, MidirAzelle, MidirJamke, MidirClaud, MidirBeowolf, MidirLex, MidirDew, LewynLewyn, LewynChulainn, LewynAzelle, LewynJamke, LewynClaud, LewynBeowolf, LewynLex, LewynDew, ChulainnChulainn, ChulainnAzelle, ChulainnJamke, ChulainnClaud, ChulainnBeowolf, ChulainnLex, ChulainnDew, AzelleAzelle, AzelleJamke, AzelleClaud, AzelleBeowolf, AzelleLex, AzelleDew, JamkeJamke, JamkeClaud, JamkeBeowolf, JamkeLex, JamkeDew, ClaudClaud, ClaudBeowolf, ClaudLex, ClaudDew, BeowolfBeowolf, BeowolfLex, BeowolfDew, LexLex, LexDew, DewDew
.char \SigurdSigurd
.char \SigurdNaoise
.char \SigurdAlec
.char \SigurdArden
.char \SigurdFinn
.char \SigurdQuan
.char \SigurdMidir
.char \SigurdLewyn
.char \SigurdChulainn
.char \SigurdAzelle
.char \SigurdJamke
.char \SigurdClaud
.char \SigurdBeowolf
.char \SigurdLex
.char \SigurdDew
.char \NaoiseNaoise
.char \NaoiseAlec
.char \NaoiseArden
.char \NaoiseFinn
.char \NaoiseQuan
.char \NaoiseMidir
.char \NaoiseLewyn
.char \NaoiseChulainn
.char \NaoiseAzelle
.char \NaoiseJamke
.char \NaoiseClaud
.char \NaoiseBeowolf
.char \NaoiseLex
.char \NaoiseDew
.char \AlecAlec
.char \AlecArden
.char \AlecFinn
.char \AlecQuan
.char \AlecMidir
.char \AlecLewyn
.char \AlecChulainn
.char \AlecAzelle
.char \AlecJamke
.char \AlecClaud
.char \AlecBeowolf
.char \AlecLex
.char \AlecDew
.char \ArdenArden
.char \ArdenFinn
.char \ArdenQuan
.char \ArdenMidir
.char \ArdenLewyn
.char \ArdenChulainn
.char \ArdenAzelle
.char \ArdenJamke
.char \ArdenClaud
.char \ArdenBeowolf
.char \ArdenLex
.char \ArdenDew
.char \FinnFinn
.char \FinnQuan
.char \FinnMidir
.char \FinnLewyn
.char \FinnChulainn
.char \FinnAzelle
.char \FinnJamke
.char \FinnClaud
.char \FinnBeowolf
.char \FinnLex
.char \FinnDew
.char \QuanQuan
.char \QuanMidir
.char \QuanLewyn
.char \QuanChulainn
.char \QuanAzelle
.char \QuanJamke
.char \QuanClaud
.char \QuanBeowolf
.char \QuanLex
.char \QuanDew
.char \MidirMidir
.char \MidirLewyn
.char \MidirChulainn
.char \MidirAzelle
.char \MidirJamke
.char \MidirClaud
.char \MidirBeowolf
.char \MidirLex
.char \MidirDew
.char \LewynLewyn
.char \LewynChulainn
.char \LewynAzelle
.char \LewynJamke
.char \LewynClaud
.char \LewynBeowolf
.char \LewynLex
.char \LewynDew
.char \ChulainnChulainn
.char \ChulainnAzelle
.char \ChulainnJamke
.char \ChulainnClaud
.char \ChulainnBeowolf
.char \ChulainnLex
.char \ChulainnDew
.char \AzelleAzelle
.char \AzelleJamke
.char \AzelleClaud
.char \AzelleBeowolf
.char \AzelleLex
.char \AzelleDew
.char \JamkeJamke
.char \JamkeClaud
.char \JamkeBeowolf
.char \JamkeLex
.char \JamkeDew
.char \ClaudClaud
.char \ClaudBeowolf
.char \ClaudLex
.char \ClaudDew
.char \BeowolfBeowolf
.char \BeowolfLex
.char \BeowolfDew
.char \LexLex
.char \LexDew
.char \DewDew
.endstruct

    structGen1LoveWLWEntry .struct DeirdreDeirdre, DeirdreEthlyn, DeirdreLachesis, DeirdreAyra, DeirdreErinys, DeirdreTailtiu, DeirdreSilvia, DeirdreEdain, DeirdreBrigid, EthlynEthlyn, EthlynLachesis, EthlynAyra, EthlynErinys, EthlynTailtiu, EthlynSilvia, EthlynEdain, EthlynBrigid, LachesisLachesis, LachesisAyra, LachesisErinys, LachesisTailtiu, LachesisSilvia, LachesisEdain, LachesisBrigid, AyraAyra, AyraErinys, AyraTailtiu, AyraSilvia, AyraEdain, AyraBrigid, ErinysErinys, ErinysTailtiu, ErinysSilvia, ErinysEdain, ErinysBrigid, TailtiuTailtiu, TailtiuSilvia, TailtiuEdain, TailtiuBrigid, SilviaSilvia, SilviaEdain, SilviaBrigid, EdainEdain, EdainBrigid, BrigidBrigid
.char \DeirdreDeirdre
.char \DeirdreEthlyn
.char \DeirdreLachesis
.char \DeirdreAyra
.char \DeirdreErinys
.char \DeirdreTailtiu
.char \DeirdreSilvia
.char \DeirdreEdain
.char \DeirdreBrigid

.char \EthlynEthlyn
.char \EthlynLachesis
.char \EthlynAyra
.char \EthlynErinys
.char \EthlynTailtiu
.char \EthlynSilvia
.char \EthlynEdain
.char \EthlynBrigid

.char \LachesisLachesis
.char \LachesisAyra
.char \LachesisErinys
.char \LachesisTailtiu
.char \LachesisSilvia
.char \LachesisEdain
.char \LachesisBrigid

.char \AyraAyra
.char \AyraErinys
.char \AyraTailtiu
.char \AyraSilvia
.char \AyraEdain
.char \AyraBrigid

.char \ErinysErinys
.char \ErinysTailtiu
.char \ErinysSilvia
.char \ErinysEdain
.char \ErinysBrigid

.char \TailtiuTailtiu
.char \TailtiuSilvia
.char \TailtiuEdain
.char \TailtiuBrigid

.char \SilviaSilvia
.char \SilviaEdain
.char \SilviaBrigid

.char \EdainEdain
.char \EdainBrigid

.char \BrigidBrigid
.endstruct

aLoveWLWBaseOffsetnumber = 50
aLoveMLMBaseOffsetnumber = 76

aLoveWLWGrowthOffsetnumber = 50
aLoveMLMGrowthOffsetnumber = 76